name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [ 2.6, 2.7, '3.0', 3.1, head, jruby, jruby-head, truffleruby, truffleruby-head ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - uses: ruby/setup-ruby@v1
          with:
            fetch-depth: 0  # for posts's lastmod
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        - run: bash tools/deploy.sh
